services:
    _defaults:
        public: false

    Oro\Bundle\CronBundle\Command\CronCommand:
        arguments:
            - '@doctrine'
            - '@oro_maintenance.maintenance'
            - '@oro_cron.helper.cron'
            - '@oro_cron.async.command_runner'
            - '@logger'
            - '%kernel.environment%'
        tags:
            - { name: console.command }

    Oro\Bundle\CronBundle\Command\CronDefinitionsLoadCommand:
        arguments:
            - '@doctrine'
            - '@Oro\Bundle\CronBundle\Loader\ScheduleTableLoader'
        tags:
            - { name: console.command }
