services:
    _defaults:
        public: true

    Oro\Bundle\ImapBundle\Controller\ConnectionController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ImapBundle\Controller\CheckConnectionController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

#    Oro\Bundle\ImapBundle\Controller\GmailAccessTokenController:
#        calls:
#            - ['setContainer', ['@Psr\Container\ContainerInterface']]
#        tags:
#            - { name: container.service_subscriber }

#    Oro\Bundle\ImapBundle\Controller\MicrosoftAccessTokenController:
#        calls:
#            - ['setContainer', ['@Psr\Container\ContainerInterface']]
#        tags:
#            - { name: container.service_subscriber }
